/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.hostproperty;

import org.w3c.dom.*;

import edu.uci.isr.xarch.*;

import java.util.*;

/**
 * DOM-Based implementation of the IHost interface.
 *
 * @author Automatically generated by xArch apigen.
 */
public class HostImpl implements IHost, DOMBased{
	
	public static final String XSD_TYPE_NSURI = HostpropertyConstants.NS_URI;
	public static final String XSD_TYPE_NAME = "Host";
	
	protected IXArch xArch;
	
	/** Tag name for ids in this object. */
	public static final String ID_ATTR_NAME = "id";
	/** Tag name for descriptions in this object. */
	public static final String DESCRIPTION_ELT_NAME = "description";
	/** Tag name for hostPropertys in this object. */
	public static final String HOST_PROPERTY_ELT_NAME = "hostProperty";
	/** Tag name for subhosts in this object. */
	public static final String SUBHOST_ELT_NAME = "subhost";
	/** Tag name for hostsComponents in this object. */
	public static final String HOSTS_COMPONENT_ELT_NAME = "hostsComponent";
	/** Tag name for hostsConnectors in this object. */
	public static final String HOSTS_CONNECTOR_ELT_NAME = "hostsConnector";
	/** Tag name for hostsGroups in this object. */
	public static final String HOSTS_GROUP_ELT_NAME = "hostsGroup";

	
	protected Element elt;
	
	private static SequenceOrder seqOrd = new SequenceOrder(
		new QName[]{
			new QName(HostpropertyConstants.NS_URI, DESCRIPTION_ELT_NAME),
			new QName(HostpropertyConstants.NS_URI, HOST_PROPERTY_ELT_NAME),
			new QName(HostpropertyConstants.NS_URI, SUBHOST_ELT_NAME),
			new QName(HostpropertyConstants.NS_URI, HOSTS_COMPONENT_ELT_NAME),
			new QName(HostpropertyConstants.NS_URI, HOSTS_CONNECTOR_ELT_NAME),
			new QName(HostpropertyConstants.NS_URI, HOSTS_GROUP_ELT_NAME)
		}
	);
	
	public HostImpl(Element elt){
		if(elt == null){
			throw new IllegalArgumentException("Element cannot be null.");
		}
		this.elt = elt;
	}

	public Node getDOMNode(){
		return elt;
	}
	
	public void setDOMNode(Node node){
		if(node.getNodeType() != Node.ELEMENT_NODE){
			throw new IllegalArgumentException("Base DOM node of this type must be an Element.");
		}
		elt = (Element)node;
	}
	
	protected static SequenceOrder getSequenceOrder(){
		return seqOrd;
	}
	
	public void setXArch(IXArch xArch){
		this.xArch = xArch;
	}
	
	public IXArch getXArch(){
		return this.xArch;
	}

	public IXArchElement cloneElement(int depth){
		synchronized(DOMUtils.getDOMLock(elt)){
			Document doc = elt.getOwnerDocument();
			if(depth == 0){
				Element cloneElt = (Element)elt.cloneNode(false);
				cloneElt = (Element)doc.importNode(cloneElt, true);
				HostImpl cloneImpl = new HostImpl(cloneElt);
				cloneImpl.setXArch(getXArch());
				return cloneImpl;
			}
			else if(depth == 1){
				Element cloneElt = (Element)elt.cloneNode(false);
				cloneElt = (Element)doc.importNode(cloneElt, true);
				HostImpl cloneImpl = new HostImpl(cloneElt);
				cloneImpl.setXArch(getXArch());
				
				NodeList nl = elt.getChildNodes();
				int size = nl.getLength();
				for(int i = 0; i < size; i++){
					Node n = nl.item(i);
					Node cloneNode = (Node)n.cloneNode(false);
					cloneNode = doc.importNode(cloneNode, true);
					cloneElt.appendChild(cloneNode);
				}
				return cloneImpl;
			}
			else /* depth = infinity */{
				Element cloneElt = (Element)elt.cloneNode(true);
				cloneElt = (Element)doc.importNode(cloneElt, true);
				HostImpl cloneImpl = new HostImpl(cloneElt);
				cloneImpl.setXArch(getXArch());
				return cloneImpl;
			}
		}
	}

	//Override 'equals' to be DOM-based...	
	public boolean equals(Object o){
		if(o == null){
			return false;
		}
		if(!(o instanceof DOMBased)){
			return super.equals(o);
		}
		DOMBased db = (DOMBased)o;
		Node dbNode = db.getDOMNode();
		return dbNode.equals(getDOMNode());
	}

	//Override 'hashCode' to be based on the underlying node
	public int hashCode(){
		return getDOMNode().hashCode();
	}

	/**
	 * For internal use only.
	 */
	private static Object makeDerivedWrapper(Element elt, String baseTypeName){
		synchronized(DOMUtils.getDOMLock(elt)){
			QName typeName = XArchUtils.getXSIType(elt);
			if(typeName == null){
				return null;
			}
			else{
				if(!DOMUtils.hasXSIType(elt, "http://www.ics.uci.edu/pub/arch/xArch/hostproperty.xsd", baseTypeName)){
					try{
						String packageTitle = XArchUtils.getPackageTitle(typeName.getNamespaceURI());
						String packageName = XArchUtils.getPackageName(packageTitle);
						String implName = XArchUtils.getImplName(packageName, typeName.getName());
						Class c = Class.forName(implName);
						java.lang.reflect.Constructor con = c.getConstructor(new Class[]{Element.class});
						Object o = con.newInstance(new Object[]{elt});
						return o;
					}
					catch(Exception e){
						//Lots of bad things could happen, but this
						//is OK, because this is best-effort anyway.
					}
				}
				return null;
			}
		}
	}

	public XArchTypeMetadata getTypeMetadata(){
		return IHost.TYPE_METADATA;
	}

	public XArchInstanceMetadata getInstanceMetadata(){
		return new XArchInstanceMetadata(XArchUtils.getPackageTitle(elt.getNamespaceURI()));
	}
	/**
	 * Set the id attribute on this object.
	 * @param id attribute value.
	 */
	public void setId(String id){
		{
			String oldValue = getId();
			if(oldValue == null ? id == null : oldValue.equals(id))
				return;
			DOMUtils.removeAttribute(elt, HostpropertyConstants.NS_URI, ID_ATTR_NAME);
			IXArch _x = getXArch();
			if(_x != null){
				_x.fireXArchEvent(
					new XArchEvent(this, 
					XArchEvent.CLEAR_EVENT,
					XArchEvent.ATTRIBUTE_CHANGED,
					"id", oldValue,
					XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this), true)
				);
			}
		}
		DOMUtils.setAttribute(elt, HostpropertyConstants.NS_URI, ID_ATTR_NAME, id);
		IXArch _x = getXArch();
		if(_x != null){
			_x.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.SET_EVENT,
				XArchEvent.ATTRIBUTE_CHANGED,
				"id", id,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
		
	/**
	 * Removes the id attribute from this object.
	 */
	public void clearId(){
		String oldValue = getId();
		if(oldValue == null)
			return;
		DOMUtils.removeAttribute(elt, HostpropertyConstants.NS_URI, ID_ATTR_NAME);
		IXArch _x = getXArch();
		if(_x != null){
			_x.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.CLEAR_EVENT,
				XArchEvent.ATTRIBUTE_CHANGED,
				"id", oldValue,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
	
	/**
	 * Gets the value of the id attribute on this object.
	 * @return id attribute's value or <code>null</code> if that
	 * attribute is not set.
	 */
	public String getId(){
		return DOMUtils.getAttributeValue(elt, HostpropertyConstants.NS_URI, ID_ATTR_NAME);
	}
	
	/**
	 * Determines if this object's id attribute has the
	 * given value.
	 * @param id value to test.
	 * @return <code>true</code> if the values match, <code>false</code> otherwise.
	 * Matching is done by string-matching.
	 */
	public boolean hasId(String id){
		return DOMUtils.objNullEq(getId(), id);
	}


	public void setDescription(edu.uci.isr.xarch.instance.IDescription value){
		if(!(value instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		{
			edu.uci.isr.xarch.instance.IDescription oldElt = getDescription();
			DOMUtils.removeChildren(elt, HostpropertyConstants.NS_URI, DESCRIPTION_ELT_NAME);
			
			IXArch context = getXArch();
			if(context != null){
				context.fireXArchEvent(
					new XArchEvent(this, 
					XArchEvent.CLEAR_EVENT,
					XArchEvent.ELEMENT_CHANGED,
					"description", oldElt,
					XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this), true)
				);
			}
		}
		Element newChildElt = (Element)(((DOMBased)value).getDOMNode());
		newChildElt = DOMUtils.cloneAndRename(newChildElt, HostpropertyConstants.NS_URI, DESCRIPTION_ELT_NAME);
		((DOMBased)value).setDOMNode(newChildElt);
		
		synchronized(DOMUtils.getDOMLock(elt)){
			elt.appendChild(newChildElt);
			DOMUtils.order(elt, getSequenceOrder());
		}
		
		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.SET_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"description", value,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
	
	public void clearDescription(){
		edu.uci.isr.xarch.instance.IDescription oldElt = getDescription();
		DOMUtils.removeChildren(elt, HostpropertyConstants.NS_URI, DESCRIPTION_ELT_NAME);
		
		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.CLEAR_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"description", oldElt,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
	
	public edu.uci.isr.xarch.instance.IDescription getDescription(){
		NodeList nl = DOMUtils.getChildren(elt, HostpropertyConstants.NS_URI, DESCRIPTION_ELT_NAME);
		if(nl.getLength() == 0){
			return null;
		}
		else{
			Element el = (Element)nl.item(0);
			IXArch de = getXArch();
			if(de != null){
				IXArchElement cachedXArchElt = de.getWrapper(el);
				if(cachedXArchElt != null){
					return (edu.uci.isr.xarch.instance.IDescription)cachedXArchElt;
				}
			}
			
			Object o = makeDerivedWrapper(el, "Description");
			if(o != null){
				try{
					((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
					if(de != null){
						de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)o));
					}
					return (edu.uci.isr.xarch.instance.IDescription)o;
				}
				catch(Exception e){}
			}
			edu.uci.isr.xarch.instance.DescriptionImpl eltImpl = new edu.uci.isr.xarch.instance.DescriptionImpl(el);
			eltImpl.setXArch(getXArch());
			if(de != null){
				de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
			}
			return eltImpl;
		}
	}
	
	public boolean hasDescription(edu.uci.isr.xarch.instance.IDescription value){
		edu.uci.isr.xarch.instance.IDescription thisValue = getDescription();
		edu.uci.isr.xarch.instance.IDescription thatValue = value;
		
		if((thisValue == null) && (thatValue == null)){
			return true;
		}
		else if((thisValue == null) && (thatValue != null)){
			return false;
		}
		else if((thisValue != null) && (thatValue == null)){
			return false;
		}
		return thisValue.isEquivalent(thatValue);
	}

	public void addHostProperty(IProperty newHostProperty){
		if(!(newHostProperty instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		Element newChildElt = (Element)(((DOMBased)newHostProperty).getDOMNode());
		newChildElt = DOMUtils.cloneAndRename(newChildElt, HostpropertyConstants.NS_URI, HOST_PROPERTY_ELT_NAME);
		((DOMBased)newHostProperty).setDOMNode(newChildElt);

		synchronized(DOMUtils.getDOMLock(elt)){
			elt.appendChild(newChildElt);
			DOMUtils.order(elt, getSequenceOrder());
		}

		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.ADD_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"hostProperty", newHostProperty,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
		
	public void addHostPropertys(Collection hostPropertys){
		for(Iterator en = hostPropertys.iterator(); en.hasNext(); ){
			IProperty elt = (IProperty)en.next();
			addHostProperty(elt);
		}
	}		
		
	public void clearHostPropertys(){
		//DOMUtils.removeChildren(elt, HostpropertyConstants.NS_URI, HOST_PROPERTY_ELT_NAME);
		Collection coll = getAllHostPropertys();
		removeHostPropertys(coll);
	}
	
	public void removeHostProperty(IProperty hostPropertyToRemove){
		if(!(hostPropertyToRemove instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		NodeList nl = DOMUtils.getChildren(elt, HostpropertyConstants.NS_URI, HOST_PROPERTY_ELT_NAME);
		for(int i = 0; i < nl.getLength(); i++){
			Node n = nl.item(i);
			if(n == ((DOMBased)hostPropertyToRemove).getDOMNode()){
				synchronized(DOMUtils.getDOMLock(elt)){
					elt.removeChild(n);
				}

				IXArch context = getXArch();
				if(context != null){
					context.fireXArchEvent(
						new XArchEvent(this, 
						XArchEvent.REMOVE_EVENT,
						XArchEvent.ELEMENT_CHANGED,
						"hostProperty", hostPropertyToRemove,
						XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
					);
				}

				return;
			}
		}
	}
	
	public void removeHostPropertys(Collection hostPropertys){
		for(Iterator en = hostPropertys.iterator(); en.hasNext(); ){
			IProperty elt = (IProperty)en.next();
			removeHostProperty(elt);
		}
	}
	
	public Collection getAllHostPropertys(){
		NodeList nl = DOMUtils.getChildren(elt, HostpropertyConstants.NS_URI, HOST_PROPERTY_ELT_NAME);
		int nlLength = nl.getLength();
		ArrayList v = new ArrayList(nlLength);
		IXArch de = getXArch();
		for(int i = 0; i < nlLength; i++){
			Element el = (Element)nl.item(i);
			boolean found = false;
			if(de != null){
				IXArchElement cachedXArchElt = de.getWrapper(el);
				if(cachedXArchElt != null){
					v.add((IProperty)cachedXArchElt);
					found = true;
				}
			}
			if(!found){
				Object o = makeDerivedWrapper(el, "Property");	
				if(o != null){
					try{
						((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)o));
						}
						v.add((IProperty)o);
					}
					catch(Exception e){
						PropertyImpl eltImpl = new PropertyImpl((Element)nl.item(i));
						eltImpl.setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
						}
						v.add(eltImpl);
					}
				}
				else{
					PropertyImpl eltImpl = new PropertyImpl((Element)nl.item(i));
					eltImpl.setXArch(getXArch());
					if(de != null){
						de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
					}
					v.add(eltImpl);
				}
			}
		}
		return v;
	}

	public boolean hasHostProperty(IProperty hostPropertyToCheck){
		Collection c = getAllHostPropertys();
		
		for(Iterator en = c.iterator(); en.hasNext(); ){
			IProperty elt = (IProperty)en.next();
			if(elt.isEquivalent(hostPropertyToCheck)){
				return true;
			}
		}
		return false;
	}
	
	public Collection hasHostPropertys(Collection hostPropertysToCheck){
		Vector v = new Vector();
		for(Iterator en = hostPropertysToCheck.iterator(); en.hasNext(); ){
			IProperty elt = (IProperty)en.next();
			v.addElement(new Boolean(hasHostProperty(elt)));
		}
		return v;
	}
		
	public boolean hasAllHostPropertys(Collection hostPropertysToCheck){
		for(Iterator en = hostPropertysToCheck.iterator(); en.hasNext(); ){
			IProperty elt = (IProperty)en.next();
			if(!hasHostProperty(elt)){
				return false;
			}
		}
		return true;
	}
	public void addSubhost(IHost newSubhost){
		if(!(newSubhost instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		Element newChildElt = (Element)(((DOMBased)newSubhost).getDOMNode());
		newChildElt = DOMUtils.cloneAndRename(newChildElt, HostpropertyConstants.NS_URI, SUBHOST_ELT_NAME);
		((DOMBased)newSubhost).setDOMNode(newChildElt);

		synchronized(DOMUtils.getDOMLock(elt)){
			elt.appendChild(newChildElt);
			DOMUtils.order(elt, getSequenceOrder());
		}

		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.ADD_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"subhost", newSubhost,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
		
	public void addSubhosts(Collection subhosts){
		for(Iterator en = subhosts.iterator(); en.hasNext(); ){
			IHost elt = (IHost)en.next();
			addSubhost(elt);
		}
	}		
		
	public void clearSubhosts(){
		//DOMUtils.removeChildren(elt, HostpropertyConstants.NS_URI, SUBHOST_ELT_NAME);
		Collection coll = getAllSubhosts();
		removeSubhosts(coll);
	}
	
	public void removeSubhost(IHost subhostToRemove){
		if(!(subhostToRemove instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		NodeList nl = DOMUtils.getChildren(elt, HostpropertyConstants.NS_URI, SUBHOST_ELT_NAME);
		for(int i = 0; i < nl.getLength(); i++){
			Node n = nl.item(i);
			if(n == ((DOMBased)subhostToRemove).getDOMNode()){
				synchronized(DOMUtils.getDOMLock(elt)){
					elt.removeChild(n);
				}

				IXArch context = getXArch();
				if(context != null){
					context.fireXArchEvent(
						new XArchEvent(this, 
						XArchEvent.REMOVE_EVENT,
						XArchEvent.ELEMENT_CHANGED,
						"subhost", subhostToRemove,
						XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
					);
				}

				return;
			}
		}
	}
	
	public void removeSubhosts(Collection subhosts){
		for(Iterator en = subhosts.iterator(); en.hasNext(); ){
			IHost elt = (IHost)en.next();
			removeSubhost(elt);
		}
	}
	
	public Collection getAllSubhosts(){
		NodeList nl = DOMUtils.getChildren(elt, HostpropertyConstants.NS_URI, SUBHOST_ELT_NAME);
		int nlLength = nl.getLength();
		ArrayList v = new ArrayList(nlLength);
		IXArch de = getXArch();
		for(int i = 0; i < nlLength; i++){
			Element el = (Element)nl.item(i);
			boolean found = false;
			if(de != null){
				IXArchElement cachedXArchElt = de.getWrapper(el);
				if(cachedXArchElt != null){
					v.add((IHost)cachedXArchElt);
					found = true;
				}
			}
			if(!found){
				Object o = makeDerivedWrapper(el, "Host");	
				if(o != null){
					try{
						((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)o));
						}
						v.add((IHost)o);
					}
					catch(Exception e){
						HostImpl eltImpl = new HostImpl((Element)nl.item(i));
						eltImpl.setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
						}
						v.add(eltImpl);
					}
				}
				else{
					HostImpl eltImpl = new HostImpl((Element)nl.item(i));
					eltImpl.setXArch(getXArch());
					if(de != null){
						de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
					}
					v.add(eltImpl);
				}
			}
		}
		return v;
	}

	public boolean hasSubhost(IHost subhostToCheck){
		Collection c = getAllSubhosts();
		
		for(Iterator en = c.iterator(); en.hasNext(); ){
			IHost elt = (IHost)en.next();
			if(elt.isEquivalent(subhostToCheck)){
				return true;
			}
		}
		return false;
	}
	
	public Collection hasSubhosts(Collection subhostsToCheck){
		Vector v = new Vector();
		for(Iterator en = subhostsToCheck.iterator(); en.hasNext(); ){
			IHost elt = (IHost)en.next();
			v.addElement(new Boolean(hasSubhost(elt)));
		}
		return v;
	}
		
	public boolean hasAllSubhosts(Collection subhostsToCheck){
		for(Iterator en = subhostsToCheck.iterator(); en.hasNext(); ){
			IHost elt = (IHost)en.next();
			if(!hasSubhost(elt)){
				return false;
			}
		}
		return true;
	}
	public IHost getSubhost(String id){
		NodeList nl = DOMUtils.getChildren(elt, HostpropertyConstants.NS_URI, SUBHOST_ELT_NAME);
		for(int i = 0; i < nl.getLength(); i++){
			
			IHost el = new HostImpl((Element)nl.item(i));
			if(DOMUtils.objNullEq(id, el.getId())){
				Element domElt = (Element)nl.item(i);
				Object o = makeDerivedWrapper(domElt, "Host");
				if(o != null){
					try{
						((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
						return (IHost)o;
					}
					catch(Exception e){}
				}
				el.setXArch(getXArch());
				return el;
			}
		}
		return null;
	}
	
	public Collection getSubhosts(Collection ids){
		//If there is an ID that does not exist, it is simply ignored.
		//You can tell if this happened if ids.size() != returned collection.size().
		Vector v = new Vector();
		for(Iterator en = ids.iterator(); en.hasNext(); ){
			String elt = (String)en.next();
			IHost retElt = getSubhost(elt);
			if(retElt != null){
				v.addElement(retElt);
			}
		}
		return v;
	}	
	
	public void addHostsComponent(IElementRef newHostsComponent){
		if(!(newHostsComponent instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		Element newChildElt = (Element)(((DOMBased)newHostsComponent).getDOMNode());
		newChildElt = DOMUtils.cloneAndRename(newChildElt, HostpropertyConstants.NS_URI, HOSTS_COMPONENT_ELT_NAME);
		((DOMBased)newHostsComponent).setDOMNode(newChildElt);

		synchronized(DOMUtils.getDOMLock(elt)){
			elt.appendChild(newChildElt);
			DOMUtils.order(elt, getSequenceOrder());
		}

		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.ADD_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"hostsComponent", newHostsComponent,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
		
	public void addHostsComponents(Collection hostsComponents){
		for(Iterator en = hostsComponents.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			addHostsComponent(elt);
		}
	}		
		
	public void clearHostsComponents(){
		//DOMUtils.removeChildren(elt, HostpropertyConstants.NS_URI, HOSTS_COMPONENT_ELT_NAME);
		Collection coll = getAllHostsComponents();
		removeHostsComponents(coll);
	}
	
	public void removeHostsComponent(IElementRef hostsComponentToRemove){
		if(!(hostsComponentToRemove instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		NodeList nl = DOMUtils.getChildren(elt, HostpropertyConstants.NS_URI, HOSTS_COMPONENT_ELT_NAME);
		for(int i = 0; i < nl.getLength(); i++){
			Node n = nl.item(i);
			if(n == ((DOMBased)hostsComponentToRemove).getDOMNode()){
				synchronized(DOMUtils.getDOMLock(elt)){
					elt.removeChild(n);
				}

				IXArch context = getXArch();
				if(context != null){
					context.fireXArchEvent(
						new XArchEvent(this, 
						XArchEvent.REMOVE_EVENT,
						XArchEvent.ELEMENT_CHANGED,
						"hostsComponent", hostsComponentToRemove,
						XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
					);
				}

				return;
			}
		}
	}
	
	public void removeHostsComponents(Collection hostsComponents){
		for(Iterator en = hostsComponents.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			removeHostsComponent(elt);
		}
	}
	
	public Collection getAllHostsComponents(){
		NodeList nl = DOMUtils.getChildren(elt, HostpropertyConstants.NS_URI, HOSTS_COMPONENT_ELT_NAME);
		int nlLength = nl.getLength();
		ArrayList v = new ArrayList(nlLength);
		IXArch de = getXArch();
		for(int i = 0; i < nlLength; i++){
			Element el = (Element)nl.item(i);
			boolean found = false;
			if(de != null){
				IXArchElement cachedXArchElt = de.getWrapper(el);
				if(cachedXArchElt != null){
					v.add((IElementRef)cachedXArchElt);
					found = true;
				}
			}
			if(!found){
				Object o = makeDerivedWrapper(el, "ElementRef");	
				if(o != null){
					try{
						((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)o));
						}
						v.add((IElementRef)o);
					}
					catch(Exception e){
						ElementRefImpl eltImpl = new ElementRefImpl((Element)nl.item(i));
						eltImpl.setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
						}
						v.add(eltImpl);
					}
				}
				else{
					ElementRefImpl eltImpl = new ElementRefImpl((Element)nl.item(i));
					eltImpl.setXArch(getXArch());
					if(de != null){
						de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
					}
					v.add(eltImpl);
				}
			}
		}
		return v;
	}

	public boolean hasHostsComponent(IElementRef hostsComponentToCheck){
		Collection c = getAllHostsComponents();
		
		for(Iterator en = c.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			if(elt.isEquivalent(hostsComponentToCheck)){
				return true;
			}
		}
		return false;
	}
	
	public Collection hasHostsComponents(Collection hostsComponentsToCheck){
		Vector v = new Vector();
		for(Iterator en = hostsComponentsToCheck.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			v.addElement(new Boolean(hasHostsComponent(elt)));
		}
		return v;
	}
		
	public boolean hasAllHostsComponents(Collection hostsComponentsToCheck){
		for(Iterator en = hostsComponentsToCheck.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			if(!hasHostsComponent(elt)){
				return false;
			}
		}
		return true;
	}
	public void addHostsConnector(IElementRef newHostsConnector){
		if(!(newHostsConnector instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		Element newChildElt = (Element)(((DOMBased)newHostsConnector).getDOMNode());
		newChildElt = DOMUtils.cloneAndRename(newChildElt, HostpropertyConstants.NS_URI, HOSTS_CONNECTOR_ELT_NAME);
		((DOMBased)newHostsConnector).setDOMNode(newChildElt);

		synchronized(DOMUtils.getDOMLock(elt)){
			elt.appendChild(newChildElt);
			DOMUtils.order(elt, getSequenceOrder());
		}

		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.ADD_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"hostsConnector", newHostsConnector,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
		
	public void addHostsConnectors(Collection hostsConnectors){
		for(Iterator en = hostsConnectors.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			addHostsConnector(elt);
		}
	}		
		
	public void clearHostsConnectors(){
		//DOMUtils.removeChildren(elt, HostpropertyConstants.NS_URI, HOSTS_CONNECTOR_ELT_NAME);
		Collection coll = getAllHostsConnectors();
		removeHostsConnectors(coll);
	}
	
	public void removeHostsConnector(IElementRef hostsConnectorToRemove){
		if(!(hostsConnectorToRemove instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		NodeList nl = DOMUtils.getChildren(elt, HostpropertyConstants.NS_URI, HOSTS_CONNECTOR_ELT_NAME);
		for(int i = 0; i < nl.getLength(); i++){
			Node n = nl.item(i);
			if(n == ((DOMBased)hostsConnectorToRemove).getDOMNode()){
				synchronized(DOMUtils.getDOMLock(elt)){
					elt.removeChild(n);
				}

				IXArch context = getXArch();
				if(context != null){
					context.fireXArchEvent(
						new XArchEvent(this, 
						XArchEvent.REMOVE_EVENT,
						XArchEvent.ELEMENT_CHANGED,
						"hostsConnector", hostsConnectorToRemove,
						XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
					);
				}

				return;
			}
		}
	}
	
	public void removeHostsConnectors(Collection hostsConnectors){
		for(Iterator en = hostsConnectors.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			removeHostsConnector(elt);
		}
	}
	
	public Collection getAllHostsConnectors(){
		NodeList nl = DOMUtils.getChildren(elt, HostpropertyConstants.NS_URI, HOSTS_CONNECTOR_ELT_NAME);
		int nlLength = nl.getLength();
		ArrayList v = new ArrayList(nlLength);
		IXArch de = getXArch();
		for(int i = 0; i < nlLength; i++){
			Element el = (Element)nl.item(i);
			boolean found = false;
			if(de != null){
				IXArchElement cachedXArchElt = de.getWrapper(el);
				if(cachedXArchElt != null){
					v.add((IElementRef)cachedXArchElt);
					found = true;
				}
			}
			if(!found){
				Object o = makeDerivedWrapper(el, "ElementRef");	
				if(o != null){
					try{
						((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)o));
						}
						v.add((IElementRef)o);
					}
					catch(Exception e){
						ElementRefImpl eltImpl = new ElementRefImpl((Element)nl.item(i));
						eltImpl.setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
						}
						v.add(eltImpl);
					}
				}
				else{
					ElementRefImpl eltImpl = new ElementRefImpl((Element)nl.item(i));
					eltImpl.setXArch(getXArch());
					if(de != null){
						de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
					}
					v.add(eltImpl);
				}
			}
		}
		return v;
	}

	public boolean hasHostsConnector(IElementRef hostsConnectorToCheck){
		Collection c = getAllHostsConnectors();
		
		for(Iterator en = c.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			if(elt.isEquivalent(hostsConnectorToCheck)){
				return true;
			}
		}
		return false;
	}
	
	public Collection hasHostsConnectors(Collection hostsConnectorsToCheck){
		Vector v = new Vector();
		for(Iterator en = hostsConnectorsToCheck.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			v.addElement(new Boolean(hasHostsConnector(elt)));
		}
		return v;
	}
		
	public boolean hasAllHostsConnectors(Collection hostsConnectorsToCheck){
		for(Iterator en = hostsConnectorsToCheck.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			if(!hasHostsConnector(elt)){
				return false;
			}
		}
		return true;
	}
	public void addHostsGroup(IElementRef newHostsGroup){
		if(!(newHostsGroup instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		Element newChildElt = (Element)(((DOMBased)newHostsGroup).getDOMNode());
		newChildElt = DOMUtils.cloneAndRename(newChildElt, HostpropertyConstants.NS_URI, HOSTS_GROUP_ELT_NAME);
		((DOMBased)newHostsGroup).setDOMNode(newChildElt);

		synchronized(DOMUtils.getDOMLock(elt)){
			elt.appendChild(newChildElt);
			DOMUtils.order(elt, getSequenceOrder());
		}

		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.ADD_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"hostsGroup", newHostsGroup,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
		
	public void addHostsGroups(Collection hostsGroups){
		for(Iterator en = hostsGroups.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			addHostsGroup(elt);
		}
	}		
		
	public void clearHostsGroups(){
		//DOMUtils.removeChildren(elt, HostpropertyConstants.NS_URI, HOSTS_GROUP_ELT_NAME);
		Collection coll = getAllHostsGroups();
		removeHostsGroups(coll);
	}
	
	public void removeHostsGroup(IElementRef hostsGroupToRemove){
		if(!(hostsGroupToRemove instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		NodeList nl = DOMUtils.getChildren(elt, HostpropertyConstants.NS_URI, HOSTS_GROUP_ELT_NAME);
		for(int i = 0; i < nl.getLength(); i++){
			Node n = nl.item(i);
			if(n == ((DOMBased)hostsGroupToRemove).getDOMNode()){
				synchronized(DOMUtils.getDOMLock(elt)){
					elt.removeChild(n);
				}

				IXArch context = getXArch();
				if(context != null){
					context.fireXArchEvent(
						new XArchEvent(this, 
						XArchEvent.REMOVE_EVENT,
						XArchEvent.ELEMENT_CHANGED,
						"hostsGroup", hostsGroupToRemove,
						XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
					);
				}

				return;
			}
		}
	}
	
	public void removeHostsGroups(Collection hostsGroups){
		for(Iterator en = hostsGroups.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			removeHostsGroup(elt);
		}
	}
	
	public Collection getAllHostsGroups(){
		NodeList nl = DOMUtils.getChildren(elt, HostpropertyConstants.NS_URI, HOSTS_GROUP_ELT_NAME);
		int nlLength = nl.getLength();
		ArrayList v = new ArrayList(nlLength);
		IXArch de = getXArch();
		for(int i = 0; i < nlLength; i++){
			Element el = (Element)nl.item(i);
			boolean found = false;
			if(de != null){
				IXArchElement cachedXArchElt = de.getWrapper(el);
				if(cachedXArchElt != null){
					v.add((IElementRef)cachedXArchElt);
					found = true;
				}
			}
			if(!found){
				Object o = makeDerivedWrapper(el, "ElementRef");	
				if(o != null){
					try{
						((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)o));
						}
						v.add((IElementRef)o);
					}
					catch(Exception e){
						ElementRefImpl eltImpl = new ElementRefImpl((Element)nl.item(i));
						eltImpl.setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
						}
						v.add(eltImpl);
					}
				}
				else{
					ElementRefImpl eltImpl = new ElementRefImpl((Element)nl.item(i));
					eltImpl.setXArch(getXArch());
					if(de != null){
						de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
					}
					v.add(eltImpl);
				}
			}
		}
		return v;
	}

	public boolean hasHostsGroup(IElementRef hostsGroupToCheck){
		Collection c = getAllHostsGroups();
		
		for(Iterator en = c.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			if(elt.isEquivalent(hostsGroupToCheck)){
				return true;
			}
		}
		return false;
	}
	
	public Collection hasHostsGroups(Collection hostsGroupsToCheck){
		Vector v = new Vector();
		for(Iterator en = hostsGroupsToCheck.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			v.addElement(new Boolean(hasHostsGroup(elt)));
		}
		return v;
	}
		
	public boolean hasAllHostsGroups(Collection hostsGroupsToCheck){
		for(Iterator en = hostsGroupsToCheck.iterator(); en.hasNext(); ){
			IElementRef elt = (IElementRef)en.next();
			if(!hasHostsGroup(elt)){
				return false;
			}
		}
		return true;
	}
	public boolean isEqual(IHost HostToCheck){
		String thisId = getId();
		String thatId = HostToCheck.getId();
		
		if((thisId == null) || (thatId == null)){
			throw new IllegalArgumentException("One of the arguments is missing an ID.");
		}
		return thisId.equals(thatId);
	}
	
	public boolean isEquivalent(IHost c){
		return (getClass().equals(c.getClass())) &&
			hasDescription(c.getDescription()) &&
			hasAllHostPropertys(c.getAllHostPropertys()) &&
			c.hasAllHostPropertys(getAllHostPropertys()) &&
			hasAllSubhosts(c.getAllSubhosts()) &&
			c.hasAllSubhosts(getAllSubhosts()) &&
			hasAllHostsComponents(c.getAllHostsComponents()) &&
			c.hasAllHostsComponents(getAllHostsComponents()) &&
			hasAllHostsConnectors(c.getAllHostsConnectors()) &&
			c.hasAllHostsConnectors(getAllHostsConnectors()) &&
			hasAllHostsGroups(c.getAllHostsGroups()) &&
			c.hasAllHostsGroups(getAllHostsGroups()) ;
	}

}
