/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.hostproperty;

import java.util.Collection;
import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * ElementRef <code>xsi:type</code> in the
 * hostproperty namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface IElementRef extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"hostproperty", "ElementRef", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createElement("ref", "instance", "XMLLink", 1, 1)},
		new XArchActionMetadata[]{});

	/**
	 * Set the ref for this ElementRef.
	 * @param value new ref
	 */
	public void setRef(edu.uci.isr.xarch.instance.IXMLLink value);

	/**
	 * Clear the ref from this ElementRef.
	 */
	public void clearRef();

	/**
	 * Get the ref from this ElementRef.
	 * @return ref
	 */
	public edu.uci.isr.xarch.instance.IXMLLink getRef();

	/**
	 * Determine if this ElementRef has the given ref
	 * @param refToCheck ref to compare
	 * @return <code>true</code> if the refs are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasRef(edu.uci.isr.xarch.instance.IXMLLink refToCheck);
	/**
	 * Determine if another ElementRef is equivalent to this one, ignoring
	 * ID's.
	 * @param ElementRefToCheck ElementRef to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * ElementRef are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(IElementRef ElementRefToCheck);

}
