/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.instancemapping;

import java.util.*;

import edu.uci.isr.xarch.*;

import org.w3c.dom.*;

import edu.uci.isr.xarch.IXArch;
import edu.uci.isr.xarch.IXArchContext;

/**
 * The context interface for the instancemapping package.
 * This interface is used to create objects that are used
 * in the instancemapping namespace.
 *
 * @author Automatically Generated by xArch apigen
 */
public interface IInstancemappingContext extends IXArchContext{

	/**
	 * Create an IBlueprint object in this namespace.
	 * @return New IBlueprint object.
	 */
	public IBlueprint createBlueprint();

	/**
	 * Brings an IBlueprint object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public IBlueprint recontextualizeBlueprint(IBlueprint value);

	/**
	 * Create an edu.uci.isr.xarch.instance.IXMLLink object in this namespace.
	 * @return New edu.uci.isr.xarch.instance.IXMLLink object.
	 */
	public edu.uci.isr.xarch.instance.IXMLLink createXMLLink();

	/**
	 * Brings an edu.uci.isr.xarch.instance.IXMLLink object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public edu.uci.isr.xarch.instance.IXMLLink recontextualizeXMLLink(edu.uci.isr.xarch.instance.IXMLLink value);

	/**
	 * Create an IMappedComponentInstance object in this namespace.
	 * @return New IMappedComponentInstance object.
	 */
	public IMappedComponentInstance createMappedComponentInstance();

	/**
	 * Brings an IMappedComponentInstance object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public IMappedComponentInstance recontextualizeMappedComponentInstance(IMappedComponentInstance value);

	/**
	 * Promote an object of type <code>edu.uci.isr.xarch.instance.IComponentInstance</code>
	 * to one of type <code>IMappedComponentInstance</code>.  xArch APIs
	 * are structured in such a way that a regular cast is not possible
	 * to change interface types, so casting must be done through these
	 * promotion functions.  If the <code>edu.uci.isr.xarch.instance.IComponentInstance</code>
	 * object wraps a DOM element that is the base type, then the 
	 * <code>xsi:type</code> of the base element is promoted.  Otherwise, 
	 * it is left unchanged.
	 *
	 * This function also emits an <CODE>XArchEvent</CODE> with type
	 * PROMOTE_TYPE.  The source for this events is the pre-promoted
	 * IXArchElement object (should no longer be used), and the
	 * target is the post-promotion object.  The target name is
	 * the name of the interface class that was the target of the
	 * promotion.
	 * 
	 * @param value Object to promote.
	 * @return Promoted object.
	 */
	public IMappedComponentInstance promoteToMappedComponentInstance(
	edu.uci.isr.xarch.instance.IComponentInstance value);

	/**
	 * Create an IMappedConnectorInstance object in this namespace.
	 * @return New IMappedConnectorInstance object.
	 */
	public IMappedConnectorInstance createMappedConnectorInstance();

	/**
	 * Brings an IMappedConnectorInstance object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public IMappedConnectorInstance recontextualizeMappedConnectorInstance(IMappedConnectorInstance value);

	/**
	 * Promote an object of type <code>edu.uci.isr.xarch.instance.IConnectorInstance</code>
	 * to one of type <code>IMappedConnectorInstance</code>.  xArch APIs
	 * are structured in such a way that a regular cast is not possible
	 * to change interface types, so casting must be done through these
	 * promotion functions.  If the <code>edu.uci.isr.xarch.instance.IConnectorInstance</code>
	 * object wraps a DOM element that is the base type, then the 
	 * <code>xsi:type</code> of the base element is promoted.  Otherwise, 
	 * it is left unchanged.
	 *
	 * This function also emits an <CODE>XArchEvent</CODE> with type
	 * PROMOTE_TYPE.  The source for this events is the pre-promoted
	 * IXArchElement object (should no longer be used), and the
	 * target is the post-promotion object.  The target name is
	 * the name of the interface class that was the target of the
	 * promotion.
	 * 
	 * @param value Object to promote.
	 * @return Promoted object.
	 */
	public IMappedConnectorInstance promoteToMappedConnectorInstance(
	edu.uci.isr.xarch.instance.IConnectorInstance value);

	/**
	 * Create an IMappedInterfaceInstance object in this namespace.
	 * @return New IMappedInterfaceInstance object.
	 */
	public IMappedInterfaceInstance createMappedInterfaceInstance();

	/**
	 * Brings an IMappedInterfaceInstance object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public IMappedInterfaceInstance recontextualizeMappedInterfaceInstance(IMappedInterfaceInstance value);

	/**
	 * Promote an object of type <code>edu.uci.isr.xarch.instance.IInterfaceInstance</code>
	 * to one of type <code>IMappedInterfaceInstance</code>.  xArch APIs
	 * are structured in such a way that a regular cast is not possible
	 * to change interface types, so casting must be done through these
	 * promotion functions.  If the <code>edu.uci.isr.xarch.instance.IInterfaceInstance</code>
	 * object wraps a DOM element that is the base type, then the 
	 * <code>xsi:type</code> of the base element is promoted.  Otherwise, 
	 * it is left unchanged.
	 *
	 * This function also emits an <CODE>XArchEvent</CODE> with type
	 * PROMOTE_TYPE.  The source for this events is the pre-promoted
	 * IXArchElement object (should no longer be used), and the
	 * target is the post-promotion object.  The target name is
	 * the name of the interface class that was the target of the
	 * promotion.
	 * 
	 * @param value Object to promote.
	 * @return Promoted object.
	 */
	public IMappedInterfaceInstance promoteToMappedInterfaceInstance(
	edu.uci.isr.xarch.instance.IInterfaceInstance value);


	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_CONTEXT,
		"instancemapping", null, null,
		new XArchPropertyMetadata[]{},
		new XArchActionMetadata[]{
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, IBlueprint.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, IBlueprint.TYPE_METADATA, IBlueprint.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, edu.uci.isr.xarch.instance.IXMLLink.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, edu.uci.isr.xarch.instance.IXMLLink.TYPE_METADATA, edu.uci.isr.xarch.instance.IXMLLink.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, IMappedComponentInstance.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, IMappedComponentInstance.TYPE_METADATA, IMappedComponentInstance.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.PROMOTE, edu.uci.isr.xarch.instance.IComponentInstance.TYPE_METADATA, IMappedComponentInstance.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, IMappedConnectorInstance.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, IMappedConnectorInstance.TYPE_METADATA, IMappedConnectorInstance.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.PROMOTE, edu.uci.isr.xarch.instance.IConnectorInstance.TYPE_METADATA, IMappedConnectorInstance.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, IMappedInterfaceInstance.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, IMappedInterfaceInstance.TYPE_METADATA, IMappedInterfaceInstance.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.PROMOTE, edu.uci.isr.xarch.instance.IInterfaceInstance.TYPE_METADATA, IMappedInterfaceInstance.TYPE_METADATA)});

}

